secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpress

services:
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb
    env_file: .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mariadb-admin", "--defaults-extra-file=/var/lib/mysql/.healthcheck.cnf", "ping"]
      start_period: 60s
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    init: true

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    image: wordpress
    env_file: .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "test", "-f", "/var/www/wordpress/wp-login.php"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    init: true

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    init: true
